### ISSUE TITLE
Is there a plan to increase support for core2.0?

### ISSUE THREAD

**Issue by Y2zz** [machine/machine.vstestadapter#80] opened 2018-03-25 14:21 UTC
Hi：@ivanz 
Is there a plan to increase support for core2.0?
Currently unable to use MSpec in core2.0

**Comment by Y2zz** [comment] 2018-07-11 16:07
hi: @robertcoltheart 
I tried to run the test and it is still not available
```
2018.07.12 00:02:45.301    WARN Element Tests.Companies.shoud_create_company was left pending after its run completion.
```

**Comment by robertcoltheart** [comment] 2018-07-12 00:55
Hi, @Y2zz can you please attach a sample project so we can reproduce and fix?

**Comment by Y2zz** [comment] 2018-07-12 15:17
@robertcoltheart 
I am very sorry, forgot to say my situation.
I am using visual studio 2017 (15.7.5), resharper 2018.1.3 can not run

**Comment by robertcoltheart** [comment] 2018-07-13 00:31
Yes, I understand. But can you please upload a zip file with a solution and code that reproduces this? I can't reproduce this locally and need your help if I am to fix this.

**Comment by Y2zz** [comment] 2018-07-14 06:23
I have created a console demo project for testing Resharper found MSpec test target
https://github.com/Y2zz/MSpec-Runtime-Test.git

**Comment by robertcoltheart** [comment] 2018-07-15 11:43
There are a couple of problems with your sample:

1. You need to reference `Microsoft.NET.Test.Sdk` in order to properly run tests
2. You should delete the `Program.cs` file. 
3. Ideally the `It` statement should actually test something like `true.ShouldBeTrue()` or something, but this is ok for now.

Once I do (1) and (2), the tests are discovered and run as normal, see below:

![image](https://user-images.githubusercontent.com/13191652/42733628-40b0d78a-8867-11e8-8099-4a4d67392f29.png)

Please provide any further amendments to your sample so that we can check if this is a genuine issue, otherwise I'll go ahead and close this.

**Comment by Y2zz** [comment] 2018-07-21 03:18
@robertcoltheart 
Sorry, I only saw the information at this time.
After further modification, the test can be run, but the relevant options for the test are not found in the right-click menu.

**Comment by robertcoltheart** [comment] 2018-07-23 05:15
This is a known issue with VS and R#. The code needs to be built first, then the option will show up. In any case, it isn't an issue within MSpec, so I'm going to close this issue.

**Closed by robertcoltheart** 2018-07-23 05:15 UTC
